name: Daily Commit

on:
  schedule:
    - cron: '0 0,8,16 * * *'  # Schedule runs every day at midnight, 8 AM, and 4 PM UTC
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: |
        echo "Updated code" >> go-green.txt
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.PAT_TOKEN }}
